# Generated by Django 3.2.9 on 2021-11-03 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=280)),
                ('username', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('verified', models.BooleanField()),
                ('sentiment_score', models.FloatField()),
                ('sentiment_magnitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.CharField(max_length=500)),
                ('tweets', models.ManyToManyField(to='tanalysis.Tweet')),
            ],
        ),
    ]
