# Generated by Django 3.2.9 on 2021-11-03 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanalysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='sentiment_magnitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='sentiment_score',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='username',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='verified',
            field=models.BooleanField(null=True),
        ),
    ]
