# Generated by Django 3.2.9 on 2021-11-20 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tanalysis', '0002_auto_20211103_2349'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15)),
            ],
        ),
        migrations.RenameField(
            model_name='query',
            old_name='search',
            new_name='query',
        ),
        migrations.RenameField(
            model_name='tweet',
            old_name='sentiment_magnitude',
            new_name='score',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='sentiment_score',
        ),
        migrations.AddField(
            model_name='tweet',
            name='engagement',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='likes',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='retweets',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='tid',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='tweets',
            field=models.ManyToManyField(blank=True, to='tanalysis.Tweet'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tanalysis.user'),
        ),
    ]
