# Generated by Django 3.2.9 on 2021-11-20 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanalysis', '0003_auto_20211120_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='user',
        ),
        migrations.AddField(
            model_name='query',
            name='users',
            field=models.ManyToManyField(blank=True, to='tanalysis.User'),
        ),
    ]
